version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: processing-postgres
    environment:
      POSTGRES_DB: processing_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  kong:
    image: kong:3.9
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong/kong.yml
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    volumes:
      - ./kong/kong.yml:/kong/kong.yml
    ports:
      - "8000:8000"  # Kong proxy
      - "8001:8001"  # Kong Admin API

volumes:
  postgres_data:
